### PR TITLE
Add arm64

### PR DESCRIPTION
**Pull request by skoudoro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by skoudoro** [comment]
@conda-forge-admin, please rerender

**Comment by skoudoro** [comment]
@conda-forge-admin, please rerender

**Comment by larsoner** [comment]
Looks like the failure here is (with some spacing and path adjustments):
```
/Users/runner/miniforge3/conda-bld/trx-python_1704767683135/work/conda_build.sh: line 4:
    /Users/runner/miniforge3/conda-bld/trx-python_1704767683135/_h_env_placehold_.../bin/python:
    Bad CPU type in executable
```
No idea what that's about...

**Comment by skoudoro** [comment]
Yes, Not sure what I can do more to force arm64.  it seems it is using another architecture which conflict with arm64. 

Searching which option needs to be added...

**Comment by larsoner** [comment]
To me it looks like you are missing these lines

https://github.com/conda-forge/openmeeg-feedstock/blob/b6bcc18ef21b56707651eaf424bfb979e61b6765/recipe/meta.yaml#L18-L22

**Comment by skoudoro** [comment]
You might be right, this is what is explain here: https://conda-forge.org/blog/2020/10/29/macos-arm64/

Let me find this locally and update this PR

**Comment by skoudoro** [comment]
@conda-forge-admin, please rerender

**Comment by skoudoro** [comment]
@conda-forge-admin, please rerender

**Comment by larsoner** [comment]
If you do have to go back to having `numpy` in the cross-compile list but looks like the error before was:
```
-   - package numpy-1.22.0-py38h9d72dae_0 requires python_abi 3.8.* *_cp38, but none of the providers can be installed
```
Something is fishy with this -- it was trying to use numpy 1.22 on Python 3.11 but for OpenMEEG this requires NumPy 1.23, and for 3.12 it uses 1.26, see the pinning scheme in the naming:

https://github.com/conda-forge/openmeeg-feedstock/tree/main/.ci_support

No idea if that'll be needed here, but figured I'd mention it in case you do have to put the `numpy` part back

**Comment by skoudoro** [comment]
Thanks! I do not think I need to put back `Numpy` since it was not initially in the `host requirements`. Let see how it goes.

**Comment by skoudoro** [comment]
All green ! Thanks for the help @larsoner.

Can you review and merge this @arokem?  This will help DIPY conda forge to move forward.

Thanks in adavance!

**Comment by arokem** [comment]
Thanks for adding this!

**Pull request merged**
