### PR TITLE
Arch Migrator with cross-compilation

### PR DESCRIPTION
**Pull request by larsoner**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

https://github.com/conda-forge/trx-python-feedstock/pull/7 with a switch to emulation.

### CODE REVIEW

**Comment by larsoner** [comment]
@conda-forge-admin, please rerender

**Comment by larsoner** [comment]
... and if the emulation doesn't work, then I think we can just skip `ppc64le` for now. Seems okay to add `aarch64` first since it works, then work on `ppc64le` later.

**Comment by larsoner** [comment]
Emulation didn't take appreciably longer than any other build, which is great! @arokem feel free to merge if you're happy.

**Comment by hoechenberger** [comment]
Wow this is amazing!!! 😻

**Comment by mfansler** [comment]
Note that this is *cross-compilation* rather than *emulation*. If you had changed to `azure`, but didn't set the build_platform to **linux_64**, then it would be emulating, and that typically has a noticeable performance hit (e.g., 6-8 times longer).

**Comment by larsoner** [comment]
Actually @arokem I'd suggest cherry-picking fc64415447b8f775fc2246c2cbc9384c75b4cd09 and 7366cbe1027a7bfc28b2479c6a6566d08950f72c rather than merging this. They say at the top of #7 that it's best to merge their PR rather than close it if possible.

**Comment by arokem** [comment]
Thanks @larsoner! Just to be clear: should I cherry pick those into #7?

**Comment by larsoner** [comment]
Yep!

**Comment by arokem** [comment]
OK - done! (I think)

**Pull request closed without merging**
